/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package patterns;

public class App {

    public static void main(String[] args) {
        SquareGenerator.generateNumericSquareOrderedVerticallyInSnakeFactionStartFromTop(5);
        System.out.println();
        SquareGenerator.generateNumericSquareOrderedVerticallyInSnakeFactionStartFromBottom(5);
    }
}
