/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package patterns;

public class App {

    public static void main(String[] args) {
        PyramidGenerator.generatePyramid(5);
    }
}
